### ISSUE TITLE
configure instructions are unclear

### ISSUE THREAD

**Issue by emmakat** [aalok-sathe/pathin#2]
I don't understand from the readme, what I am supposed to do with pathin configure. At this prompt: Bash config file [~/.bashrc]:  

I'm wondering if you can provide more context or sane defaults, as to what to do at this step

**Comment by aalok-sathe** [comment]
either leave it as-is for the default value (~/.bashrc), or enter a full
path to your bash config (e.g. ~/.bash_profile, or ~/.zshrc, etc.)
